//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace SS_General_Trading.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Name is Required!")]
        public string Name { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage ="This field is required comment.")]
        public string Comments { get; set; }
    }
}
